os: linux
dist: bionic
services:
  - xvfb
install:
  - sudo snap install snapcraft --classic
  - sudo snap install multipass --beta --classic
  - git clone --recurse-submodules --depth 3 --single-branch --branch develop https://github.com/cyberbotics/webots.git
script:
  - sudo snapcraft
