os: linux
dist: bionic
language: generic
sudo: required
services:
  - xvfb
install:
  - sudo snap install snapcraft --classic
  - git clone --recurse-submodules --depth 3 --single-branch --branch $WEBOTS_TARGET_BRANCH https://github.com/cyberbotics/webots.git
script:
  - snapcraft --destructive-mode
