# unset WEBOTS_HOME
# unset LD_LIBRARY_PATH
# unset JAVA_HOME
# snapcraft --destructive-mode
# snap install --dangerous webots_R2019b-rev1_amd64.snap
# webots
# snap uninstall webots
# snapcraft login
# snapcraft push --release=edge webots_R2019b-rev1_amd64.snap
# snap install webots

name: webots
title: Webots
base: core18
version: 'R2019b-rev1'
summary: Webots is a free and open-source 3D robot simulator
description: |
  Webots is a free and open-source 3D robot simulator.
  It allows you to create 3D simulation models of robots interacting with their
  environment through sensors and actuators. Libraries of robots, sensors,
  actuators and objects are provided, but you can create your own. Collision
  detections, rigid body dynamics and fluid dynamics rely on a modified version
  of the ODE physics engine. The robot controller programs can be written
  outside of Webots in C, C++, Python, ROS, Java or MATLAB using a simple API.
  Webots features a 3D web interface allowing you to publish simulations online.
icon: webots.png
license: Apache-2.0
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
architectures:
  - build-on: amd64
    run-on: amd64

layout:
  /etc/openal:
    bind: $SNAP/etc/openal
  /usr/include:
    bind: $SNAP/usr/include
  /usr/lib:
    bind: $SNAP/usr/lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/applications:
    bind: $SNAP/usr/share/applications
  /usr/share/bash-completion:
    bind: $SNAP/usr/share/bash-completion
  /usr/share/binfmts:
    bind: $SNAP/usr/share/binfmts
  /usr/share/bug:
    bind: $SNAP/usr/share/bug
  /usr/share/build-essential:
    bind: $SNAP/usr/share/build-essential
  /usr/share/dbus-1:
    bind: $SNAP/usr/share/dbus-1
  /usr/share/distro-info:
    bind: $SNAP/usr/share/distro-info
  /usr/share/doc:
    bind: $SNAP/usr/share/doc
  /usr/share/doc-base:
    bind: $SNAP/usr/share/doc-base
  /usr/share/dpkg:
    bind: $SNAP/usr/share/dpkg
  /usr/share/drirc.d:
    bind: $SNAP/usr/share/drirc.d
  /usr/share/fcitx:
    bind: $SNAP/usr/share/fcitx
  /usr/share/ffmpeg:
    bind: $SNAP/usr/share/ffmpeg
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/gcc-8:
    bind: $SNAP/usr/share/gcc-8
  /usr/share/GConf:
    bind: $SNAP/usr/share/GConf
  /usr/share/gdb:
    bind: $SNAP/usr/share/gdb
  /usr/share/gettext:
    bind: $SNAP/usr/share/gettext
  /usr/share/glib-2.0:
    bind: $SNAP/usr/share/glib-2.0
  /usr/share/gtk-engines:
    bind: $SNAP/usr/share/gtk-engines
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/java:
    bind: $SNAP/usr/share/java
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/share/libsensors4:
    bind: $SNAP/usr/share/libsensors4
  /usr/share/libthai:
    bind: $SNAP/usr/share/libthai
  /usr/share/lintian:
    bind: $SNAP/usr/share/lintian
  /usr/share/locale:
    bind: $SNAP/usr/share/locale
  /usr/share/man:
    bind: $SNAP/usr/share/man
  /usr/share/mime:
    bind: $SNAP/usr/share/mime
  /usr/share/openal:
    bind: $SNAP/usr/share/openal
  /usr/share/perl:
    bind: $SNAP/usr/share/perl
  /usr/share/perl5:
    bind: $SNAP/usr/share/perl5
  /usr/share/pixmaps:
    bind: $SNAP/usr/share/pixmaps
  /usr/share/pkgconfig:
    bind: $SNAP/usr/share/pkgconfig
  /usr/share/presage:
    bind: $SNAP/usr/share/presage
  /usr/share/proj:
    bind: $SNAP/usr/share/proj
  /usr/share/pyshared:
    bind: $SNAP/usr/share/pyshared
  /usr/share/python3:
    bind: $SNAP/usr/share/python3
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /usr/share/themes:
    bind: $SNAP/usr/share/themes
  /usr/share/thumbnailers:
    bind: $SNAP/usr/share/thumbnailers
  /usr/share/upstart:
    bind: $SNAP/usr/share/upstart
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/share/xml:
    bind: $SNAP/usr/share/xml

parts:
  desktop-gtk3:
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk2.0-0
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - locales-all
    - xdg-user-dirs
    - ibus-gtk3
    - libibus-1.0-5
    - fcitx-frontend-gtk3

  webots:
    build-packages:
      - cmake
      - curl
      - execstack
      - ffmpeg
      - g++
      - git
      - libassimp-dev
      - libavcodec-extra
      - libboost-dev
      - libfreeimage-dev
      - libfreetype6-dev
      - libgd-dev
      - libglib2.0-dev
      - libglu1-mesa-dev
      - libjpeg8-dev
      - libpci-dev
      - libpng-dev
      - libreadline-dev
      - libssh-gcrypt-dev
      - libssl1.0-dev
      - libtiff5-dev
      - libusb-dev
      - libxml2-dev
      - libzip-dev
      - libzzip-0-13
      - lsb-release
      - npm
      - openjdk-8-jdk
      - pbzip2
      - python-pip
      - python2.7-dev
      - python3.6-dev
      - python3.7-dev
      - swig
      - unzip
      - wget
      - xvfb
      - zip
    plugin: make
    build-environment:
      - WEBOTS_HOME: "$SNAPCRAFT_PART_BUILD"
    # When building locally, uncomment the following line:
    source: /home/olivier/webots
    # When building from snapcraft.io, uncomment the following lines:
    # source: https://github.com/omichel/webots
    # source-type: git
    # source-branch: feature-snapcraft-build
    # source-tag: R2019b
    # source-depth: 1
    stage-packages:
      - openjdk-11-jdk
      - build-essential
      - libc6-dev
      - ffmpeg
      - libasn1-8-heimdal
      - libasound2
      - libatk1.0-0
      - libavutil55
      - libblkid1
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libcrystalhd3
      - libcurl3-gnutls
      - libdbus-1-3
      - libdouble-conversion1
      - libfreeimage3
      - libfreetype6
      - libgcc1
      - libgcrypt20
      - libgd3
      - libgeos-3.6.2
      - libgfortran4
      - libglib2.0-0
      - libgl1
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - libgpg-error0
      - libgsm1
      - libgssapi3-heimdal
      - libgtk-3-0
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libjpeg8-dev
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libltdl7
      - liblzma5
      - libminizip1
      - libmount1
      - libmp3lame0
      - libnghttp2-14
      - libnss3
      - libnuma1
      - libopenal-data
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopus0
      - libpci3
      - libpcre3
      - libproj12
      - libpsl5
      - libpulse-mainloop-glib0
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libselinux1
      - libshine3
      - libslang2
      - libsnappy1v5
      - libsndio6.1
      - libsoxr0
      - libspeex1
      - libssh-dev
      - libssh-gcrypt-4
      - libstdc++6
      - libswresample2
      - libsystemd0
      - libtheora0
      - libtinfo5
      - libtwolame0
      - libudev1
      - libuuid1
      - libva2
      - libva-drm2
      - libva-x11-2
      - libvdpau1
      - libvo-amrwbenc0
      - libwavpack1
      - libwind0-heimdal
      - libx11-data
      - libx11-xcb1
      - libx265-146
      - libxaw7
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xkb1
      - libxft2
      - libxkbcommon-x11-0
      - libxrandr2
      - libxrender1
      - libxslt1.1
      - libxss1
      - libxtst6
      - libxvidcore4
      - liblz4-1
      - libzip-dev
      - libzvbi0
      - libzzip-0-13
      - lsb-release
      - util-linux
      - zlib1g

apps:
  webots:
    plugs: [browser-support, desktop, desktop-legacy, gsettings, hardware-observe, hidraw, hostname-control, joystick, wayland, unity7, x11, opengl, pulseaudio, home, network]
    desktop: usr/share/webots/resources/webots.desktop
    command: desktop-launch $SNAP/usr/share/webots/webots
